# Generated by Django 3.2.15 on 2022-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinemuseum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='year_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
