# Generated by Django 3.2.15 on 2022-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinemuseum', '0002_alter_user_detail_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
